version: 2

registries:
  nuget.org:
    type: nuget-feed
    url: "https://api.nuget.org/v3/index.json"
  telerik.com:
    type: nuget-feed
    url: "https://nuget.telerik.com/v3/index.json"
    username: "api-key"
    password: "${{ secrets.TELERIK_KEY }}"

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/TramTimes.Aspire.Host"
      - "/TramTimes.Aspire.Services"
      - "/TramTimes.Cache.Jobs"
      - "/TramTimes.Database.Jobs"
      - "/TramTimes.Search.Jobs"
      - "/TramTimes.Web.Api"
      - "/TramTimes.Web.Tests"
      - "/TramTimes.Web.Utilities"
    registries:
      - nuget.org
      - telerik.com
    schedule:
      interval: "weekly"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "philvessey"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "Telerik.UI.for.Blazor"

  - package-ecosystem: "nuget"
    directories:
      - "/TramTimes.Web.Site"
    registries:
      - telerik.com
    schedule:
      interval: "monthly"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "philvessey"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-name: "Telerik.UI.for.Blazor"