name: Clean

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Cache builder
        run: |
          REPOSITORY="cache-builder"

          MANIFESTS=$(az acr manifest list-metadata \
            --registry ${{ secrets.AZURE_REGISTRY_NAME }} \
            --name $REPOSITORY \
            --orderby time_desc \
            --query '[].digest' \
            --output json)

          echo "$MANIFESTS" | jq -r '.[30:][]' | \
          xargs -I {} az acr repository delete \
          --name ${{ secrets.AZURE_REGISTRY_NAME }} \
          --image $REPOSITORY@{} \
          --yes 2>/dev/null || true

      - name: Database builder
        run: |
          REPOSITORY="database-builder"

          MANIFESTS=$(az acr manifest list-metadata \
            --registry ${{ secrets.AZURE_REGISTRY_NAME }} \
            --name $REPOSITORY \
            --orderby time_desc \
            --query '[].digest' \
            --output json)

          echo "$MANIFESTS" | jq -r '.[30:][]' | \
          xargs -I {} az acr repository delete \
          --name ${{ secrets.AZURE_REGISTRY_NAME }} \
          --image $REPOSITORY@{} \
          --yes 2>/dev/null || true

      - name: Search builder
        run: |
          REPOSITORY="search-builder"

          MANIFESTS=$(az acr manifest list-metadata \
            --registry ${{ secrets.AZURE_REGISTRY_NAME }} \
            --name $REPOSITORY \
            --orderby time_desc \
            --query '[].digest' \
            --output json)

          echo "$MANIFESTS" | jq -r '.[30:][]' | \
          xargs -I {} az acr repository delete \
          --name ${{ secrets.AZURE_REGISTRY_NAME }} \
          --image $REPOSITORY@{} \
          --yes 2>/dev/null || true

      - name: Web api
        run: |
          REPOSITORY="web-api"

          MANIFESTS=$(az acr manifest list-metadata \
            --registry ${{ secrets.AZURE_REGISTRY_NAME }} \
            --name $REPOSITORY \
            --orderby time_desc \
            --query '[].digest' \
            --output json)

          echo "$MANIFESTS" | jq -r '.[30:][]' | \
          xargs -I {} az acr repository delete \
          --name ${{ secrets.AZURE_REGISTRY_NAME }} \
          --image $REPOSITORY@{} \
          --yes 2>/dev/null || true

      - name: Web site
        run: |
          REPOSITORY="web-site"

          MANIFESTS=$(az acr manifest list-metadata \
            --registry ${{ secrets.AZURE_REGISTRY_NAME }} \
            --name $REPOSITORY \
            --orderby time_desc \
            --query '[].digest' \
            --output json)

          echo "$MANIFESTS" | jq -r '.[30:][]' | \
          xargs -I {} az acr repository delete \
          --name ${{ secrets.AZURE_REGISTRY_NAME }} \
          --image $REPOSITORY@{} \
          --yes 2>/dev/null || true